#!/usr/bin/env python3
"""Printable four-slot straight tongue dovetail half-shell for tom v2 link brackets.

This intentionally keeps the slot interface simple: raised rounded tongues
locate in the nominal lower and upper lightening slots, while side return rails
wrap around the bracket plate to the link center plane. The default generated
part is the male half of an all-printed PLA dovetail; a matching female half is
generated by link_bracket_slot_pair_straight_socket_sample.py.
"""

from __future__ import annotations

import sys
from pathlib import Path

import build123d

PRINTABLE_DIR = Path(__file__).resolve().parent
V2_DIR = PRINTABLE_DIR.parent
PARTS_DIR = V2_DIR / "parts"
if str(PARTS_DIR) not in sys.path:
    sys.path.insert(0, str(PARTS_DIR))

import link_bracket as lb
import link_common as lc
from v2_variant_common import finish_part


PART_NAME = Path(__file__).stem
PLASTIC_COLOR = build123d.Color(1.0, 1.0, 1.0, 1.0)

FIT_CLEARANCE_TOTAL_MM = 0.0
SLOT_LENGTH_CLEARANCE_TOTAL_MM = 0.0
ORIGINAL_EXTRA_THROUGH_DEPTH_MM = 0.40

SLOT_WIDTH_MM = lb.SLOT_WIDTH_MM
TOP_SLOT_WIDTH_MM = lb.TOP_SLOT_WIDTH_MM
LOWER_SLOT_LENGTH_MM = lb.LOWER_SLOT_LENGTH_MM
TOP_SLOT_LENGTH_MM = lb.TOP_SLOT_LENGTH_MM
SHEET_THICKNESS_MM = lc.SHEET_THICKNESS_MM
LOWER_SLOT_PAIR_CENTER_X_MM = 0.5 * (
    lb.LOWER_SLOT_CENTER_X_MM[0] + lb.LOWER_SLOT_CENTER_X_MM[1]
)
TOP_SLOT_PAIR_CENTER_X_MM = 0.5 * (
    lb.TOP_SLOT_CENTER_X_MM[0] + lb.TOP_SLOT_CENTER_X_MM[1]
)
LOWER_SLOT_PAIR_CENTER_SPACING_MM = (
    lb.LOWER_SLOT_CENTER_X_MM[1] - lb.LOWER_SLOT_CENTER_X_MM[0]
)
TOP_SLOT_PAIR_CENTER_SPACING_MM = (
    lb.TOP_SLOT_CENTER_X_MM[1] - lb.TOP_SLOT_CENTER_X_MM[0]
)
TOP_SECTION_OFFSET_X_MM = lb.TOP_SLOT_CENTER_Z_MM - lb.LOWER_SLOT_CENTER_Z_MM
TOP_SECTION_OFFSET_Y_MM = LOWER_SLOT_PAIR_CENTER_X_MM - TOP_SLOT_PAIR_CENTER_X_MM

TONGUE_WIDTH_MM = SLOT_WIDTH_MM - FIT_CLEARANCE_TOTAL_MM
TOP_TONGUE_WIDTH_MM = TOP_SLOT_WIDTH_MM - FIT_CLEARANCE_TOTAL_MM
ORIGINAL_TONGUE_INSERTION_DEPTH_MM = SHEET_THICKNESS_MM + ORIGINAL_EXTRA_THROUGH_DEPTH_MM
TONGUE_INSERTION_DEPTH_MM = ORIGINAL_TONGUE_INSERTION_DEPTH_MM
EXTRA_THROUGH_DEPTH_MM = TONGUE_INSERTION_DEPTH_MM - SHEET_THICKNESS_MM
BASE_END_MARGIN_MM = 2.0
BASE_SIDE_MARGIN_MM = 6.0
LOWER_TONGUE_LENGTH_MM = LOWER_SLOT_LENGTH_MM - SLOT_LENGTH_CLEARANCE_TOTAL_MM
TOP_TONGUE_LENGTH_MM = TOP_SLOT_LENGTH_MM - SLOT_LENGTH_CLEARANCE_TOTAL_MM
LOWER_BASE_LENGTH_MM = LOWER_TONGUE_LENGTH_MM + 2.0 * BASE_END_MARGIN_MM
TOP_BASE_LENGTH_MM = TOP_TONGUE_LENGTH_MM + 2.0 * BASE_END_MARGIN_MM
LOWER_BASE_WIDTH_MM = (
    LOWER_SLOT_PAIR_CENTER_SPACING_MM + TONGUE_WIDTH_MM + 2.0 * BASE_SIDE_MARGIN_MM
)
TOP_BASE_WIDTH_MM = (
    TOP_SLOT_PAIR_CENTER_SPACING_MM + TOP_TONGUE_WIDTH_MM + 2.0 * BASE_SIDE_MARGIN_MM
)
# In the printable link assembly, connector local X maps to assembly world Z.
# These world-Z limits match the link bracket plate extents in the printable
# assembly: link_bracket_right/left #o1.3 and #o1.4.
BASE_TARGET_WORLD_Z_MIN_MM = 0.0
BASE_TARGET_WORLD_Z_MAX_MM = 144.538516
BASE_TARGET_LOCAL_X_MIN_MM = BASE_TARGET_WORLD_Z_MIN_MM - lb.LOWER_SLOT_CENTER_Z_MM
BASE_TARGET_LOCAL_X_MAX_MM = BASE_TARGET_WORLD_Z_MAX_MM - lb.LOWER_SLOT_CENTER_Z_MM
BASE_X_MIN_MM = min(
    -0.5 * LOWER_BASE_LENGTH_MM,
    TOP_SECTION_OFFSET_X_MM - 0.5 * TOP_BASE_LENGTH_MM,
    BASE_TARGET_LOCAL_X_MIN_MM,
)
BASE_X_MAX_MM = max(
    0.5 * LOWER_BASE_LENGTH_MM,
    TOP_SECTION_OFFSET_X_MM + 0.5 * TOP_BASE_LENGTH_MM,
    BASE_TARGET_LOCAL_X_MAX_MM,
)
# Connector local Y maps to bracket/assembly -X. Keep the wrap rails just
# outside the nearby servo envelopes so the shell wraps the plates instead of
# intersecting the servo bodies.
BASE_TARGET_WORLD_X_MIN_MM = -20.0
BASE_TARGET_WORLD_X_MAX_MM = 36.0
BASE_TARGET_LOCAL_Y_MIN_MM = LOWER_SLOT_PAIR_CENTER_X_MM - BASE_TARGET_WORLD_X_MAX_MM
BASE_TARGET_LOCAL_Y_MAX_MM = LOWER_SLOT_PAIR_CENTER_X_MM - BASE_TARGET_WORLD_X_MIN_MM
BASE_Y_MIN_MM = min(
    -0.5 * LOWER_BASE_WIDTH_MM,
    TOP_SECTION_OFFSET_Y_MM - 0.5 * TOP_BASE_WIDTH_MM,
    BASE_TARGET_LOCAL_Y_MIN_MM,
)
BASE_Y_MAX_MM = max(
    0.5 * LOWER_BASE_WIDTH_MM,
    TOP_SECTION_OFFSET_Y_MM + 0.5 * TOP_BASE_WIDTH_MM,
    BASE_TARGET_LOCAL_Y_MAX_MM,
)
BASE_LENGTH_MM = BASE_X_MAX_MM - BASE_X_MIN_MM
BASE_WIDTH_MM = BASE_Y_MAX_MM - BASE_Y_MIN_MM
BASE_THICKNESS_MM = 1.8
SHELL_HALF_DEPTH_MM = lb.LEG_OUTER_Y_MM + BASE_THICKNESS_MM
WRAP_RAIL_WIDTH_MM = 7.0
WRAP_RAIL_OVERLAP_MM = 0.05
OUTER_CORNER_FILLET_MM = 7.0
END_COVERAGE_THICKNESS_MM = 2.2
SERVO_HALF_Y_CLEARANCE_MM = lb.LEG_OUTER_Y_MM
END_COVERAGE_DEPTH_MM = SHELL_HALF_DEPTH_MM - SERVO_HALF_Y_CLEARANCE_MM
DOVETAIL_Y_CENTERS_MM = (
    BASE_Y_MIN_MM - 0.5 * WRAP_RAIL_WIDTH_MM,
    BASE_Y_MAX_MM + 0.5 * WRAP_RAIL_WIDTH_MM,
)
DOVETAIL_X_END_RELIEF_MM = 0.0
DOVETAIL_NECK_WIDTH_MM = 3.2
DOVETAIL_HEAD_WIDTH_MM = 4.8
DOVETAIL_ENGAGEMENT_DEPTH_MM = 2.2
DOVETAIL_ROOT_OVERLAP_MM = 0.15
DOVETAIL_CLEARANCE_MM = 0.0
DOVETAIL_MALE_X_MIN_MM = BASE_X_MIN_MM + DOVETAIL_X_END_RELIEF_MM
DOVETAIL_MALE_X_MAX_MM = BASE_X_MAX_MM - DOVETAIL_X_END_RELIEF_MM
DOVETAIL_SOCKET_X_MIN_MM = BASE_X_MIN_MM - 1.0
DOVETAIL_SOCKET_X_MAX_MM = BASE_X_MAX_MM + 1.0
LOWER_TONGUE_CENTERS_MM = (
    (0.0, -0.5 * LOWER_SLOT_PAIR_CENTER_SPACING_MM),
    (0.0, 0.5 * LOWER_SLOT_PAIR_CENTER_SPACING_MM),
)
TOP_TONGUE_CENTERS_MM = (
    (TOP_SECTION_OFFSET_X_MM, TOP_SECTION_OFFSET_Y_MM - 0.5 * TOP_SLOT_PAIR_CENTER_SPACING_MM),
    (TOP_SECTION_OFFSET_X_MM, TOP_SECTION_OFFSET_Y_MM + 0.5 * TOP_SLOT_PAIR_CENTER_SPACING_MM),
)


def _slot_prism_xy(
    *,
    length: float,
    width: float,
    z_min: float,
    z_max: float,
    rotation_deg: float = 0.0,
) -> build123d.Shape:
    with build123d.BuildPart() as part:
        with build123d.BuildSketch(build123d.Plane.XY):
            build123d.SlotOverall(width=length, height=width, rotation=rotation_deg)
        build123d.extrude(amount=z_max - z_min)
    return part.part.moved(build123d.Location((0.0, 0.0, z_min)))


def _box(
    *,
    x_min: float,
    x_max: float,
    y_min: float,
    y_max: float,
    z_min: float,
    z_max: float,
) -> build123d.Solid:
    return build123d.Solid.make_box(
        x_max - x_min,
        y_max - y_min,
        z_max - z_min,
        plane=build123d.Plane(origin=build123d.Vector(x_min, y_min, z_min)),
    )


def _base_sheet() -> build123d.Shape:
    return _box(
        x_min=BASE_X_MIN_MM,
        x_max=BASE_X_MAX_MM,
        y_min=BASE_Y_MIN_MM,
        y_max=BASE_Y_MAX_MM,
        z_min=0.0,
        z_max=BASE_THICKNESS_MM,
    )


def _end_coverage_caps() -> list[build123d.Shape]:
    y_min = BASE_Y_MIN_MM - WRAP_RAIL_WIDTH_MM
    y_max = BASE_Y_MAX_MM + WRAP_RAIL_WIDTH_MM
    return [
        _box(
            x_min=BASE_X_MIN_MM,
            x_max=BASE_X_MIN_MM + END_COVERAGE_THICKNESS_MM,
            y_min=y_min,
            y_max=y_max,
            z_min=0.0,
            z_max=END_COVERAGE_DEPTH_MM,
        ),
        _box(
            x_min=BASE_X_MAX_MM - END_COVERAGE_THICKNESS_MM,
            x_max=BASE_X_MAX_MM,
            y_min=y_min,
            y_max=y_max,
            z_min=0.0,
            z_max=END_COVERAGE_DEPTH_MM,
        ),
    ]


def _wrap_rails() -> list[build123d.Shape]:
    return [
        _box(
            x_min=BASE_X_MIN_MM,
            x_max=BASE_X_MAX_MM,
            y_min=BASE_Y_MIN_MM - WRAP_RAIL_WIDTH_MM,
            y_max=BASE_Y_MIN_MM + WRAP_RAIL_OVERLAP_MM,
            z_min=0.0,
            z_max=SHELL_HALF_DEPTH_MM,
        ),
        _box(
            x_min=BASE_X_MIN_MM,
            x_max=BASE_X_MAX_MM,
            y_min=BASE_Y_MAX_MM - WRAP_RAIL_OVERLAP_MM,
            y_max=BASE_Y_MAX_MM + WRAP_RAIL_WIDTH_MM,
            z_min=0.0,
            z_max=SHELL_HALF_DEPTH_MM,
        ),
    ]


def _straight_tongue(*, length: float, width: float) -> build123d.Shape:
    return _slot_prism_xy(
        length=length,
        width=width,
        z_min=BASE_THICKNESS_MM,
        z_max=BASE_THICKNESS_MM + TONGUE_INSERTION_DEPTH_MM,
    )


def _dovetail_prism_x(
    *,
    x_min: float,
    x_max: float,
    y_center: float,
    z_root: float,
    z_tip: float,
    root_width: float,
    tip_width: float,
) -> build123d.Shape:
    with build123d.BuildPart() as part:
        with build123d.BuildSketch(build123d.Plane.YZ):
            build123d.Polygon(
                (y_center - 0.5 * root_width, z_root),
                (y_center + 0.5 * root_width, z_root),
                (y_center + 0.5 * tip_width, z_tip),
                (y_center - 0.5 * tip_width, z_tip),
                align=None,
            )
        build123d.extrude(amount=x_max - x_min)
    return part.part.moved(build123d.Location((x_min, 0.0, 0.0)))


def _dovetail_male_rails() -> list[build123d.Shape]:
    return [
        _dovetail_prism_x(
            x_min=DOVETAIL_MALE_X_MIN_MM,
            x_max=DOVETAIL_MALE_X_MAX_MM,
            y_center=center_y,
            z_root=SHELL_HALF_DEPTH_MM - DOVETAIL_ROOT_OVERLAP_MM,
            z_tip=SHELL_HALF_DEPTH_MM + DOVETAIL_ENGAGEMENT_DEPTH_MM,
            root_width=DOVETAIL_NECK_WIDTH_MM,
            tip_width=DOVETAIL_HEAD_WIDTH_MM,
        )
        for center_y in DOVETAIL_Y_CENTERS_MM
    ]


def _dovetail_socket_cutters() -> list[build123d.Shape]:
    cutters: list[build123d.Shape] = []
    opening_width = DOVETAIL_NECK_WIDTH_MM + 2.0 * DOVETAIL_CLEARANCE_MM
    captured_width = DOVETAIL_HEAD_WIDTH_MM + 2.0 * DOVETAIL_CLEARANCE_MM
    for center_y in DOVETAIL_Y_CENTERS_MM:
        cutters.append(
            _dovetail_prism_x(
                x_min=DOVETAIL_SOCKET_X_MIN_MM,
                x_max=DOVETAIL_SOCKET_X_MAX_MM,
                y_center=center_y,
                z_root=SHELL_HALF_DEPTH_MM + DOVETAIL_CLEARANCE_MM,
                z_tip=(
                    SHELL_HALF_DEPTH_MM
                    - DOVETAIL_ENGAGEMENT_DEPTH_MM
                    - DOVETAIL_CLEARANCE_MM
                ),
                root_width=opening_width,
                tip_width=captured_width,
            )
        )
    return cutters


def _outside_face_corner_edges(shell: build123d.Shape) -> build123d.ShapeList[build123d.Edge]:
    outer_y_values = (
        BASE_Y_MIN_MM - WRAP_RAIL_WIDTH_MM,
        BASE_Y_MAX_MM + WRAP_RAIL_WIDTH_MM,
    )
    edges = shell.edges().filter_by(build123d.Axis.X).filter_by(
        lambda edge: abs(edge.center().Z) < 0.05
        and abs(edge.length - BASE_LENGTH_MM) < 0.05
        and any(abs(edge.center().Y - y) < 0.05 for y in outer_y_values)
    )
    if len(edges) != 2:
        raise RuntimeError(
            "Expected two outside face corner edges to fillet, "
            f"found {len(edges)}"
        )
    return edges


def build_step(*, dovetail_role: str = "male") -> build123d.Shape:
    if DOVETAIL_MALE_X_MIN_MM >= DOVETAIL_MALE_X_MAX_MM:
        raise ValueError("Dovetail end relief is longer than the connector")
    if DOVETAIL_HEAD_WIDTH_MM >= WRAP_RAIL_WIDTH_MM:
        raise ValueError("Dovetail head must fit inside the wrap rail width")
    if DOVETAIL_NECK_WIDTH_MM >= DOVETAIL_HEAD_WIDTH_MM:
        raise ValueError("Dovetail neck must be narrower than the captured head")
    if (
        DOVETAIL_HEAD_WIDTH_MM + 2.0 * DOVETAIL_CLEARANCE_MM
        >= WRAP_RAIL_WIDTH_MM - 1.0
    ):
        raise ValueError("Dovetail socket leaves too little rail wall for PLA")
    if DOVETAIL_ENGAGEMENT_DEPTH_MM + DOVETAIL_CLEARANCE_MM >= SHELL_HALF_DEPTH_MM:
        raise ValueError("Dovetail engagement is deeper than the shell half")
    if TONGUE_WIDTH_MM <= 0.0:
        raise ValueError("Fit clearance is larger than the bracket slot width")
    if TOP_TONGUE_WIDTH_MM <= 0.0:
        raise ValueError("Fit clearance is larger than the top bracket slot width")
    if TONGUE_WIDTH_MM > SLOT_WIDTH_MM:
        raise ValueError("Tongue width must not exceed the bracket slot")
    if TOP_TONGUE_WIDTH_MM > TOP_SLOT_WIDTH_MM:
        raise ValueError("Top tongue width must not exceed the top bracket slot")
    if LOWER_TONGUE_LENGTH_MM > LOWER_SLOT_LENGTH_MM:
        raise ValueError("Lower tongue length must not exceed the lower bracket slot")
    if TOP_TONGUE_LENGTH_MM > TOP_SLOT_LENGTH_MM:
        raise ValueError("Top tongue length must not exceed the top bracket slot")
    if TONGUE_INSERTION_DEPTH_MM <= SHEET_THICKNESS_MM:
        raise ValueError("Tongue insertion depth must pass through the bracket sheet")
    if abs(TOP_SLOT_PAIR_CENTER_SPACING_MM - LOWER_SLOT_PAIR_CENTER_SPACING_MM) > 0.01:
        raise ValueError(
            f"Top slot pair spacing {TOP_SLOT_PAIR_CENTER_SPACING_MM:.3f} mm "
            f"does not match lower slot spacing {LOWER_SLOT_PAIR_CENTER_SPACING_MM:.3f} mm"
        )

    sample: build123d.Shape = _base_sheet()
    for rail in _wrap_rails():
        sample = sample.fuse(rail)
    for cap in _end_coverage_caps():
        sample = sample.fuse(cap)

    for center_x, center_y in LOWER_TONGUE_CENTERS_MM:
        tongue = _straight_tongue(
            length=LOWER_TONGUE_LENGTH_MM,
            width=TONGUE_WIDTH_MM,
        ).moved(build123d.Location((center_x, center_y, 0.0)))
        sample = sample.fuse(tongue)
    for center_x, center_y in TOP_TONGUE_CENTERS_MM:
        tongue = _straight_tongue(
            length=TOP_TONGUE_LENGTH_MM,
            width=TOP_TONGUE_WIDTH_MM,
        ).moved(build123d.Location((center_x, center_y, 0.0)))
        sample = sample.fuse(tongue)

    if dovetail_role == "male":
        for rail in _dovetail_male_rails():
            sample = sample.fuse(rail)
    elif dovetail_role == "female":
        for cutter in _dovetail_socket_cutters():
            sample = sample.cut(cutter)
    else:
        raise ValueError(f"Unsupported dovetail_role {dovetail_role!r}")

    sample = sample.fillet(
        OUTER_CORNER_FILLET_MM,
        _outside_face_corner_edges(sample),
    )

    solids = sample.solids()
    if len(solids) != 1:
        raise RuntimeError(f"Expected one printable sample solid, found {len(solids)}")

    sample = finish_part(sample, PART_NAME, printable=True)
    sample.color = PLASTIC_COLOR
    bb = sample.bounding_box()
    print(
        "Link bracket four-slot straight sample "
        f"envelope={bb.size.X:.3f} x {bb.size.Y:.3f} x {bb.size.Z:.3f} mm; "
        f"lower_tongues=2x {LOWER_TONGUE_LENGTH_MM:.3f} x {TONGUE_WIDTH_MM:.3f} x "
        f"{TONGUE_INSERTION_DEPTH_MM:.3f} mm, "
        f"top_tongues=2x {TOP_TONGUE_LENGTH_MM:.3f} x {TOP_TONGUE_WIDTH_MM:.3f} x "
        f"{TONGUE_INSERTION_DEPTH_MM:.3f} mm, "
        f"slot_width={SLOT_WIDTH_MM:.3f} mm, total_clearance={FIT_CLEARANCE_TOTAL_MM:.3f} mm, "
        f"lower_slot_length={LOWER_SLOT_LENGTH_MM:.3f} mm, "
        f"top_slot_length={TOP_SLOT_LENGTH_MM:.3f} mm, "
        f"base_sheet={BASE_LENGTH_MM:.3f} x {BASE_WIDTH_MM:.3f} mm, "
        f"assembly_z_span={BASE_TARGET_WORLD_Z_MIN_MM:.3f}..{BASE_TARGET_WORLD_Z_MAX_MM:.3f} mm, "
        f"shell_half_depth={SHELL_HALF_DEPTH_MM:.3f} mm, "
        f"outer_corner_fillet={OUTER_CORNER_FILLET_MM:.3f} mm, "
        f"dovetail_role={dovetail_role}"
    )
    print(
        "Straight insertion depth "
        f"{TONGUE_INSERTION_DEPTH_MM:.3f} mm from sheet_thickness={SHEET_THICKNESS_MM:.4f} mm "
        f"+ extra_depth={EXTRA_THROUGH_DEPTH_MM:.3f} mm; "
        f"top section offset=({TOP_SECTION_OFFSET_X_MM:.3f}, {TOP_SECTION_OFFSET_Y_MM:.3f}) mm; "
        f"seam rails={WRAP_RAIL_WIDTH_MM:.3f} mm wide with "
        f"{len(DOVETAIL_Y_CENTERS_MM)} continuous dovetail slide rails, "
        f"neck={DOVETAIL_NECK_WIDTH_MM:.3f} mm, "
        f"head={DOVETAIL_HEAD_WIDTH_MM:.3f} mm, "
        f"engagement={DOVETAIL_ENGAGEMENT_DEPTH_MM:.3f} mm, "
        f"clearance={DOVETAIL_CLEARANCE_MM:.3f} mm"
    )
    return sample


def gen_step() -> dict[str, object]:
    return {
        "shape": build_step(),
    }


if __name__ == "__main__":
    gen_step()
