changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Maintenance
      labels:
        - dependencies
        - documentation
        - maintenance
    - title: Other Changes
      labels:
        - "*"
